# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Compiler_config = debug
  Interpreter_config = debug
  Tests_config = debug
endif
ifeq ($(config),release)
  Compiler_config = release
  Interpreter_config = release
  Tests_config = release
endif

PROJECTS := Compiler Interpreter Tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Compiler:
ifneq (,$(Compiler_config))
	@echo "==== Building Compiler ($(Compiler_config)) ===="
	@${MAKE} --no-print-directory -C Compiler -f Makefile config=$(Compiler_config)
endif

Interpreter: Compiler
ifneq (,$(Interpreter_config))
	@echo "==== Building Interpreter ($(Interpreter_config)) ===="
	@${MAKE} --no-print-directory -C Interpreter -f Makefile config=$(Interpreter_config)
endif

Tests: Compiler
ifneq (,$(Tests_config))
	@echo "==== Building Tests ($(Tests_config)) ===="
	@${MAKE} --no-print-directory -C Tests -f Makefile config=$(Tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C Compiler -f Makefile clean
	@${MAKE} --no-print-directory -C Interpreter -f Makefile clean
	@${MAKE} --no-print-directory -C Tests -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Compiler"
	@echo "   Interpreter"
	@echo "   Tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"